export default {
  'app.name': 'MORGET', 'common.loading': 'Loading...', 'common.confirm': 'Confirm', 'common.cancel': 'Cancel', 'common.success': 'Success', 'common.error': 'Error',
  'nav.plugins': 'Plugin Management', 'nav.settings': 'System Settings', 'nav.market': 'Plugin Market', 'nav.creator': 'Creator Center', 'nav.wallet': 'G Coin Wallet', 'nav.logout': 'Log Out',
  'auth.subtitle': 'Log in to sync your plugins and G Coin assets', 'auth.login': 'Log in with WorkOS',
  'plugins.title': 'Installed Plugins', 'plugins.count': '({count})', 'plugins.install': 'Install Plugin', 'plugins.uninstall': 'Uninstall', 'plugins.uninstall.confirm': 'Are you sure you want to uninstall {name}?', 'plugins.empty': 'No plugins', 'plugins.install.success': 'Plugin {name} installed successfully', 'plugins.install.failed': 'Installation failed: {error}', 'plugins.uninstall.success': 'Uninstalled successfully', 'plugins.uninstall.failed': 'Uninstallation failed: {error}', 'plugins.toggle.failed': 'Toggle failed: {error}',
  'market.search': 'Search plugins...', 'market.back': 'Back to List', 'market.detail_view': 'Stay for 10 seconds to earn 5 G Coins...', 'market.download_btn': 'Download & Install',
  'creator.auth_github': 'Connect GitHub Account', 'creator.upload_title': 'Upload New Plugin Version', 'creator.select_repo': 'Select GitHub Repository', 'creator.version': 'Version (e.g. 1.0.0)', 'creator.file_path': 'Plugin File (.mgpn / .mgp)', 'creator.browse': 'Browse...', 'creator.upload_btn': 'Confirm Upload & Publish', 'creator.missing_fields': 'Please select a repository and choose a file',
  'wallet.balance': 'Current Balance', 'wallet.history': 'Transaction History',
  'settings.tab.general': 'General', 'settings.tab.appearance': 'Appearance', 'settings.tab.performance': 'Performance', 'settings.tab.graphics': 'Graphics', 'settings.tab.storage': 'Storage', 'settings.general.title': 'Basic Settings', 'settings.general.language': 'Language', 'settings.general.language.hint': 'Takes effect immediately', 'settings.general.autoUpdate': 'Auto Update', 'settings.general.autoUpdate.hint': 'Install automatically in background', 'settings.appearance.title': 'Appearance', 'settings.appearance.theme': 'Theme', 'settings.appearance.theme.dark': 'Dark', 'settings.appearance.theme.light': 'Light', 'settings.appearance.theme.system': 'System', 'settings.appearance.scale': 'Scale', 'settings.appearance.scale.current': 'Current: {value}%', 'settings.performance.title': 'Performance', 'settings.performance.loading': 'Loading Mode', 'settings.performance.loading.hint': 'Balance memory and speed', 'settings.performance.loading.stream': 'Stream', 'settings.performance.loading.full': 'Full', 'settings.performance.gpu': 'GPU', 'settings.performance.gpu.hint': 'Graphics Processor', 'settings.performance.gpu.auto': 'Auto', 'settings.performance.gpu.integrated': 'Integrated', 'settings.performance.gpu.dedicated': 'Dedicated', 'settings.graphics.title': 'Graphics', 'settings.graphics.fps': 'FPS', 'settings.graphics.fps.hint': 'Limit', 'settings.graphics.fps.unlimited': 'Unlimited', 'settings.graphics.fps.value': '{value} FPS', 'settings.graphics.vsync': 'V-Sync', 'settings.graphics.vsync.hint': 'Prevent tearing', 'settings.graphics.premiumUI': 'Premium UI', 'settings.graphics.premiumUI.hint': 'Shadows and animations', 'settings.storage.title': 'Storage', 'settings.storage.downloadPath': 'Download Path', 'settings.storage.downloadPath.change': 'Change', 'settings.storage.cache': 'Cache', 'settings.storage.cache.size': 'Size: {size} MB', 'settings.storage.cache.clear': 'Clear', 'settings.storage.cache.cleared': 'Cleared {size} MB',
  'lang.zh-TW': '繁體中文', 'lang.zh-CN': '简体中文', 'lang.en-US': 'English'
};
