export default {
  'app.name': 'MORGET', 'common.loading': '加载中...', 'common.confirm': '确认', 'common.cancel': '取消', 'common.success': '成功', 'common.error': '错误',
  'nav.plugins': '插件管理', 'nav.settings': '系统设置', 'nav.market': '插件市场', 'nav.creator': '创作者中心', 'nav.wallet': 'G币钱包', 'nav.logout': '退出账号',
  'auth.subtitle': '登录以同步您的插件与 G 币资产', 'auth.login': '使用 WorkOS 登录',
  'plugins.title': '已安装插件', 'plugins.count': '({count})', 'plugins.install': '安装插件', 'plugins.uninstall': '卸载', 'plugins.uninstall.confirm': '确定卸载 {name} 吗？', 'plugins.empty': '暂无插件', 'plugins.install.success': '插件 {name} 安装成功', 'plugins.install.failed': '安装失败：{error}', 'plugins.uninstall.success': '卸载成功', 'plugins.uninstall.failed': '卸载失败：{error}', 'plugins.toggle.failed': '切换失败：{error}',
  'market.search': '搜索插件...', 'market.back': '返回列表', 'market.detail_view': '停留 10 秒即可获得 5 G 币...', 'market.download_btn': '下载并安装',
  'creator.auth_github': '连接 GitHub 账号', 'creator.upload_title': '上传新版本插件', 'creator.select_repo': '选择 GitHub 仓库', 'creator.version': '版本号 (例如 1.0.0)', 'creator.file_path': '插件文件 (.mgpn / .mgp)', 'creator.browse': '浏览...', 'creator.upload_btn': '确认上传并发布', 'creator.missing_fields': '请选择仓库并选择文件',
  'wallet.balance': '当前余额', 'wallet.history': '交易记录',
  'settings.tab.general': '常规', 'settings.tab.appearance': '外观', 'settings.tab.performance': '性能', 'settings.tab.graphics': '画面', 'settings.tab.storage': '存储', 'settings.general.title': '基本设置', 'settings.general.language': '语言', 'settings.general.language.hint': '即时生效', 'settings.general.autoUpdate': '自动更新', 'settings.general.autoUpdate.hint': '后台自动安装', 'settings.appearance.title': '外观', 'settings.appearance.theme': '主题', 'settings.appearance.theme.dark': '深色', 'settings.appearance.theme.light': '浅色', 'settings.appearance.theme.system': '系统', 'settings.appearance.scale': '缩放', 'settings.appearance.scale.current': '当前：{value}%', 'settings.performance.title': '性能', 'settings.performance.loading': '加载模式', 'settings.performance.loading.hint': '权衡内存与速度', 'settings.performance.loading.stream': '流加载', 'settings.performance.loading.full': '全量', 'settings.performance.gpu': 'GPU', 'settings.performance.gpu.hint': '图形处理器', 'settings.performance.gpu.auto': '自动', 'settings.performance.gpu.integrated': '核显', 'settings.performance.gpu.dedicated': '独显', 'settings.graphics.title': '画面', 'settings.graphics.fps': 'FPS', 'settings.graphics.fps.hint': '上限', 'settings.graphics.fps.unlimited': '无限制', 'settings.graphics.fps.value': '{value} FPS', 'settings.graphics.vsync': '垂直同步', 'settings.graphics.vsync.hint': '防止撕裂', 'settings.graphics.premiumUI': '精美UI', 'settings.graphics.premiumUI.hint': '阴影与动画', 'settings.storage.title': '存储', 'settings.storage.downloadPath': '下载路径', 'settings.storage.downloadPath.change': '更改', 'settings.storage.cache': '缓存', 'settings.storage.cache.size': '大小：{size} MB', 'settings.storage.cache.clear': '清理', 'settings.storage.cache.cleared': '已清理 {size} MB',
  'lang.zh-TW': '繁体中文', 'lang.zh-CN': '简体中文', 'lang.en-US': 'English'
};
