export default {
  'app.name': 'MORGET', 'common.loading': '載入中...', 'common.confirm': '確認', 'common.cancel': '取消', 'common.success': '成功', 'common.error': '錯誤',
  'nav.plugins': '插件管理', 'nav.settings': '系統設置', 'nav.market': '插件市場', 'nav.creator': '創作者中心', 'nav.wallet': 'G幣錢包', 'nav.logout': '登出帳號',
  'auth.subtitle': '登錄以同步您的插件與 G 幣資產', 'auth.login': '使用 WorkOS 登錄',
  'plugins.title': '已安裝插件', 'plugins.count': '({count})', 'plugins.install': '安裝插件', 'plugins.uninstall': '卸載', 'plugins.uninstall.confirm': '確定卸載 {name} 嗎？', 'plugins.empty': '暫無插件', 'plugins.install.success': '插件 {name} 安裝成功', 'plugins.install.failed': '安裝失敗：{error}', 'plugins.uninstall.success': '卸載成功', 'plugins.uninstall.failed': '卸載失敗：{error}', 'plugins.toggle.failed': '切換失敗：{error}',
  'market.search': '搜尋插件...', 'market.back': '返回列表', 'market.detail_view': '停留 10 秒即可獲得 5 G 幣...', 'market.download_btn': '下載並安裝',
  'creator.auth_github': '連接 GitHub 帳號', 'creator.upload_title': '上傳新版本插件', 'creator.select_repo': '選擇 GitHub 倉庫', 'creator.version': '版本號 (例如 1.0.0)', 'creator.file_path': '插件文件 (.mgpn / .mgp)', 'creator.browse': '瀏覽...', 'creator.upload_btn': '確認上傳並發布', 'creator.missing_fields': '請選擇倉庫並選擇文件',
  'wallet.balance': '當前餘額', 'wallet.history': '交易紀錄',
  'settings.tab.general': '常規', 'settings.tab.appearance': '外觀', 'settings.tab.performance': '性能', 'settings.tab.graphics': '畫面', 'settings.tab.storage': '存儲', 'settings.general.title': '基本設置', 'settings.general.language': '語言', 'settings.general.language.hint': '即時生效', 'settings.general.autoUpdate': '自動更新', 'settings.general.autoUpdate.hint': '後台自動安裝', 'settings.appearance.title': '外觀', 'settings.appearance.theme': '主題', 'settings.appearance.theme.dark': '深色', 'settings.appearance.theme.light': '淺色', 'settings.appearance.theme.system': '系統', 'settings.appearance.scale': '縮放', 'settings.appearance.scale.current': '當前：{value}%', 'settings.performance.title': '性能', 'settings.performance.loading': '加載模式', 'settings.performance.loading.hint': '權衡內存與速度', 'settings.performance.loading.stream': '流加載', 'settings.performance.loading.full': '全量', 'settings.performance.gpu': 'GPU', 'settings.performance.gpu.hint': '圖形處理器', 'settings.performance.gpu.auto': '自動', 'settings.performance.gpu.integrated': '核顯', 'settings.performance.gpu.dedicated': '獨顯', 'settings.graphics.title': '畫面', 'settings.graphics.fps': 'FPS', 'settings.graphics.fps.hint': '上限', 'settings.graphics.fps.unlimited': '無限制', 'settings.graphics.fps.value': '{value} FPS', 'settings.graphics.vsync': '垂直同步', 'settings.graphics.vsync.hint': '防止撕裂', 'settings.graphics.premiumUI': '精美UI', 'settings.graphics.premiumUI.hint': '陰影與動畫', 'settings.storage.title': '存儲', 'settings.storage.downloadPath': '下載路徑', 'settings.storage.downloadPath.change': '更改', 'settings.storage.cache': '緩存', 'settings.storage.cache.size': '大小：{size} MB', 'settings.storage.cache.clear': '清理', 'settings.storage.cache.cleared': '已清理 {size} MB',
  'lang.zh-TW': '繁體中文', 'lang.zh-CN': '簡體中文', 'lang.en-US': 'English'
};
